{
  "openapi": "3.0.3",
  "info": {
    "title": "Bey Dev Docs",
    "version": "1.0.0"
  },
  "paths": {
    "/v1/avatar": {
      "get": {
        "security": [
          {
            "APIKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "title": "Response List Avatars V1 Avatar Get",
                  "items": {
                    "$ref": "#/components/schemas/AvatarResponseModel"
                  }
                },
                "examples": {
                  "example": {
                    "value": [
                      {
                        "id": "01234567-89ab-cdef-0123-456789abcdef",
                        "name": "John Doe"
                      }
                    ]
                  }
                }
              }
            },
            "description": "Successful Response"
          }
        },
        "deprecated": false
      }
    },
    "/v1/session": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SessionRequestModel"
              },
              "examples": {
                "example": {
                  "value": {
                    "avatar_id": "01234567-89ab-cdef-0123-456789abcdef",
                    "livekit_url": "wss://<your-domain>.livekit.cloud",
                    "livekit_token": "<your-livekit-token>"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "APIKeyHeader": []
          }
        ],
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SessionResponseModel"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "01234567-89ab-cdef-0123-456789abcdef",
                      "created_at": "2022-01-01T00:00:00Z",
                      "avatar_id": "01234567-89ab-cdef-0123-456789abcdef",
                      "livekit_url": "wss://<your-domain>.livekit.cloud",
                      "livekit_token": "<your-livekit-token>"
                    }
                  }
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                },
                "examples": {
                  "example": {
                    "value": {
                      "detail": [
                        {
                          "loc": [
                            "<string>"
                          ],
                          "msg": "<string>",
                          "type": "<string>"
                        }
                      ]
                    }
                  }
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "deprecated": false
      },
      "get": {
        "security": [
          {
            "APIKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "title": "Response List Session V1 Session Get",
                  "items": {
                    "$ref": "#/components/schemas/SessionResponseModel"
                  }
                },
                "examples": {
                  "example": {
                    "value": [
                      {
                        "id": "01234567-89ab-cdef-0123-456789abcdef",
                        "created_at": "2022-01-01T00:00:00Z",
                        "avatar_id": "01234567-89ab-cdef-0123-456789abcdef",
                        "livekit_url": "wss://<your-domain>.livekit.cloud",
                        "livekit_token": "<your-livekit-token>"
                      }
                    ]
                  }
                }
              }
            },
            "description": "Successful Response"
          }
        },
        "deprecated": false
      }
    },
    "/v1/session/{id}": {
      "get": {
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Id"
            }
          }
        ],
        "security": [
          {
            "APIKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SessionResponseModel"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": "01234567-89ab-cdef-0123-456789abcdef",
                      "created_at": "2022-01-01T00:00:00Z",
                      "avatar_id": "01234567-89ab-cdef-0123-456789abcdef",
                      "livekit_url": "wss://<your-domain>.livekit.cloud",
                      "livekit_token": "<your-livekit-token>"
                    }
                  }
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                },
                "examples": {
                  "example": {
                    "value": {
                      "detail": [
                        {
                          "loc": [
                            "<string>"
                          ],
                          "msg": "<string>",
                          "type": "<string>"
                        }
                      ]
                    }
                  }
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "deprecated": false
      }
    }
  },
  "servers": [
    {
      "url": "https://api.bey.dev",
      "description": "API Server"
    }
  ],
  "components": {
    "schemas": {
      "AvatarResponseModel": {
        "properties": {
          "id": {
            "type": "string",
            "title": "Id",
            "description": "The unique identifier (ID) of the avatar.",
            "examples": [
              "01234567-89ab-cdef-0123-456789abcdef"
            ]
          },
          "name": {
            "type": "string",
            "title": "Name",
            "description": "The name of the avatar.",
            "examples": [
              "John Doe"
            ]
          }
        },
        "type": "object",
        "required": [
          "id",
          "name"
        ],
        "title": "AvatarResponseModel",
        "description": "Represents a Beyond Presence Avatar."
      },
      "ValidationError": {
        "properties": {
          "loc": {
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "type": "array",
            "title": "Location"
          },
          "msg": {
            "type": "string",
            "title": "Message"
          },
          "type": {
            "type": "string",
            "title": "Error Type"
          }
        },
        "type": "object",
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "title": "ValidationError"
      },
      "SessionRequestModel": {
        "$ref": "#/components/schemas/SessionRequestModel"
      },
      "SessionResponseModel": {
        "properties": {
          "id": {
            "type": "string",
            "title": "Id",
            "description": "The unique identifier (ID) of the session.",
            "examples": [
              "01234567-89ab-cdef-0123-456789abcdef"
            ]
          },
          "created_at": {
            "type": "string",
            "format": "date-time",
            "title": "Created At",
            "description": "The timestamp of when the session was created.",
            "examples": [
              "2022-01-01T00:00:00Z"
            ]
          },
          "avatar_id": {
            "type": "string",
            "title": "Avatar Id",
            "description": "The ID of the avatar used in the session.",
            "examples": [
              "01234567-89ab-cdef-0123-456789abcdef"
            ]
          },
          "livekit_url": {
            "type": "string",
            "title": "Livekit Url",
            "description": "The LiveKit URL you chose when creating your LiveKit project.",
            "examples": [
              "wss://<your-domain>.livekit.cloud"
            ]
          },
          "livekit_token": {
            "type": "string",
            "title": "Livekit Token",
            "description": "The LiveKit token used to join your LiveKit room.",
            "examples": [
              "<your-livekit-token>"
            ]
          }
        },
        "type": "object",
        "required": [
          "id",
          "created_at",
          "avatar_id",
          "livekit_url",
          "livekit_token"
        ],
        "title": "SessionResponseModel",
        "description": "Represents a Beyond Presence Real-Time API session."
      },
      "HTTPValidationError": {
        "$ref": "#/components/schemas/HTTPValidationError"
      }
    },
    "securitySchemes": {
      "APIKeyHeader": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-KEY"
      }
    }
  }
}